library: webclient
useJakartaEe: true
interfaceOnly: true
basePackage: openapi.client.support_api.v1
modelPackage: openapi.client.support_api.v1.model
apiPackage: openapi.client.support_api.v1.api
invokerPackage: openapi.client.support_api.v1.invoker
openApiNullable: false
hideGenerationTimestamp: true
java8: true
#dateLibrary: java8-localdatetime
dateLibrary: java8
useTags: true
serializableModel: true
useBeanValidation: true
useRuntimeException: true
booleanGetterPrefix: is
implicitHeaders: true